apiVersion: v2
appVersion: 0.1.0
description: An operator for Managing Sftpgo
home: https://github.com/zlepper/sftpgo-k8s-operator
keywords:
  - operator
  - sftpgo
kubeVersion: ">= 1.25.0-0"
name: sftpgo-operator
sources:
  - https://github.com/zlepper/sftpgo-k8s-operator
version: 0.1.0
