apiVersion: sftpgo.zlepper.dk/v1alpha1
kind: SftpgoServer
metadata:
  name: sftpgo
spec:
  replicas: 1
  labels:
    my_label: rhdh
  configuration:
    httpd:
      bindings:
        - port: 8383
    sftpd:
      bindings:
        - port: 2222

---
apiVersion: sftpgo.zlepper.dk/v1alpha1
kind: SftpgoUser
metadata:
  name: sftpgo-user
spec:
  configuration:
    username: sftpgo-user-but-better
    password: sftpgo-user
    enabled: Enabled
    globalPermissions:
    - all
  sftpgoServerReference:
    name: sftpgo
    overrideValues:
      url: http://localhost:50962/
