apiVersion: sftpgo.digizuite.com/v1alpha1
kind: SftpgoServer
metadata:
  name: sftpgo
spec:
  replicas: 1
  labels:
    my_label: rhdh
  configuration:
    httpd:
      bindings:
        - port: 8383
    sftpd:
      bindings:
        - port: 2222

---
apiVersion: sftpgo.digizuite.com/v1alpha1
kind: SftpgoUser
metadata:
  name: sftpgo-user
spec:
  configuration:
    username: sftpgo-user-but-better
    password: sftpgo-user
    enabled: Enabled
    globalPermissions:
    - all
    homeDir: "/srv/sftpgo/data/sftpgo-user-but-better"
    virtualFolders:
      - name: sftpgo-folder
        virtualPath: "/foo/bar"
  sftpgoServerReference:
    name: sftpgo
    overrideValues:
      url: http://localhost:50962/
---
apiVersion: sftpgo.digizuite.com/v1alpha1
kind: SftpgoFolder
metadata:
  name: sftpgo-folder
spec:
  sftpgoServerReference:
    name: sftpgo
    overrideValues:
      url: http://localhost:50962/
  configuration:
    filesystem:
      azureBlobStorage:
        authorization:
          sharedKey:
            container: "sftpgo"
            accountKey: "A5atlwr9RV2mvwrHXZOfH41rdvJ9wrOJAVdb9NKpfebjw2t0VU7tG8/kH9lRsK00M+2gq7mknADw+AStp0RstA=="
            accountName: "dgz4120c3080183"
    name: crded-folder10
---
apiVersion: sftpgo.digizuite.com/v1alpha1
kind: SftpgoAdmin
metadata:
  name: sftpgo-admin
spec:
  sftpgoServerReference:
    name: sftpgo
    overrideValues:
      url: http://localhost:50962/
  configuration:
    password: SuperDuperSecurePassword
    permissions:
    - all
    username: "rhdh-admin"
    description: "This is rhdh's admin user, and updated"
    enabled: Enabled
    email: "rhdh@digizuite.com"
