apiVersion: v2
appVersion: 2.5.0
description: An operator for Managing Sftpgo
home: https://github.com/digizuite/sftpgo-k8s-operator
keywords:
  - operator
  - sftpgo
kubeVersion: ">= 1.25.0-0"
name: sftpgo-operator
sources:
  - https://github.com/digizuite/sftpgo-k8s-operator
version: 0.1.8
icon: https://sftpgo.com/assets/img/logo.png